CREATE DATABASE IF NOT EXISTS WorkList DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;

USE DATABASE WorkList;

CREATE TABLE IF NOT EXISTS Tasklist (
TaskID int(11) NOT NULL,
  ID int(11) NOT NULL,
  `Name` varchar(255) DEFAULT NULL,
  ExpectedTime int(11) NOT NULL DEFAULT '0',
  ActualTime int(11) NOT NULL DEFAULT '0',
  Finished tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS Workplace (
ID int(11) NOT NULL,
  `Name` varchar(255) NOT NULL,
  Progress tinyint(4) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE Tasklist ADD PRIMARY KEY (TaskID), ADD UNIQUE KEY TaskID (TaskID), ADD KEY Tasklist_ibfk_1 (ID);
ALTER TABLE Workplace ADD PRIMARY KEY (ID);


ALTER TABLE Tasklist MODIFY TaskID int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE Workplace MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE Tasklist ADD CONSTRAINT Tasklist_ibfk_1 FOREIGN KEY (ID) REFERENCES Workplace (ID) ON DELETE CASCADE;
